alphagov/govuk-accounts-explore-prototype-1

app/routes.js, app/views/account/manage.html, app/views/account/sign-in-to-another-service.html, app/views/explore-header.html, app/views/includes/print-notifications.html
if in doubt, create temporary nunjucks variables and set defaults
=> fixing bugs for tests

app/views/explore-header.html
We updated the desktop button href but not the mobile one.
Doh
=> Make mobile button sign in match desktop

app/assets/sass/explore-header.scss
Still has the issue that topics nudge under the logo.
=> Fix breakpoints from out and out breaking

app/routes.js, app/views/layout.html, app/views/tasks.html
Added list of changes
Changed layout template to have a link to tasks page
Added new route to sign someone out and send them to the homepage
=> task lists page

app/views/account/sign-in-to-another-service.html
changed CSS to make styling better
=> New sign in page

app/assets/sass/accounts.scss
swizzy hover action when in the active state, and now doesn't conflict with the print button in mobile
=> button hover state/mobile alignment

app/views/tasks.html
now with 'Coronavirus: how to stay safe and help prevent the spread' since the RAG status one already has a email updates button.
=> new starting point for task one

app/routes.js, app/views/layout-traditional.html, app/views/tasks.html
Added proper list of tasks for reference
=> tasks page and refined journeys

app/routes.js, app/views/account/sign-in-to-another-service.html
Will need to style to make it work with the new ideas (also not doing top 5 for now)
=> search is now working!

app/routes.js, app/views/account/_account.html, app/views/account/sign-up/confirm.html, app/views/tasks.html
Sign out now works
Confirm page shows the name of the page
Task list has pages for task 3
=> Start of tidy up of journeys

app/filters.js, app/routes.js, app/views/tasks.html
=> fixed bug with filtering

app/routes.js, app/views/layout.html, app/views/notify/_template.html, app/views/notify/confirm.html, app/views/notify/merged.html, app/views/notify/subscribed.html, app/views/notify/welcome.html, app/views/tasks.html
adding emails at HTML in the prototype so that we have a fallback if Notify goes down
=> emails for tasks

app/routes.js, app/views/account/2fa.html, app/views/account/sign-up/check-email.html, app/views/account/sign-up/check-phone.html, app/views/account/sign-up/confirm.html, app/views/account/sign-up/created.html, app/views/includes/ur-tasks.html, app/views/layout-traditional.html, app/views/layout.html, app/views/notify/sms.html
All pages now have a link at the bottom to get back to tasks. There are also appropriate links to the emails on pages if there's a problem
=> adding better links for tasks

app/views/account/sign-up/created.html
Added content for the created account screen from auth
=> Created account content

app/views/account/2fa.html, app/views/account/password.html, app/views/account/sign-in.html, app/views/account/sign-up/check-email.html, app/views/account/sign-up/check-phone.html, app/views/account/sign-up/confirm.html, app/views/account/sign-up/create-password.html, app/views/account/sign-up/created.html, app/views/account/sign-up/email.html, app/views/account/sign-up/enter-phone.html, app/views/account/sign-up/index.html
=> turned off feedback on auth pages

app/assets/sass/accounts.scss, app/assets/sass/application.scss, app/views/account/sign-in-to-another-service.html
Fixed link styling and added a link to govuk emails on sign into a service page. Fixed hover state colour on notifications button.
=> Changes to sorting hat and notifications button

app/data/session-data-defaults.js
This reverts commit a2582209d1925932ab251505e9fa15ed105da3ee.
=> Back to mailbox 1

app/data/session-data-defaults.js
This reverts commit 48165408d2526121a567ffe31cb1081eb0e186f4.
=> Revert "inbox 1"

app/routes.js, app/views/account/manage-emails.html
May need to look at a better way to pre-pop merged emails
=> added existing topics pages as reference

app/assets/sass/application.scss, app/views/account/sign-in-to-another-service.html
Added passenger locator and childcare accounts.
Updated design to be more compact
=> Updated Sign into a government service page

app/views/account/security.html
Removed:
- services that use your data
- sign in codes
Privacy notice left where it is for now but will be changed when new place is confirmed
=> Minimal security and privacy page

app/views/account/_account.html, app/views/account/security.html
Privacy information removed and title changed in different places to just be "security" (no privacy)
=> pare down security page

app/config.js
turn back on again afterwards!
=> Turn off password for research

app/data/session-data-defaults.js, app/views/tasks.html
Turned on prototype with emails and hidden fields
=> Final amends for testing

app/routes.js, app/views/includes/success.html
Now updated page title to say "Success:" at top of page
=> Added success on page flash

app/views/sign-in.html
Sign in page linked out to gov.uk - changing to just be local for now
=> update all links to be local

app/data/session-data-defaults.js
=> Switched emailbox

app/data/session-data-defaults.js
This reverts commit 4185eaf2120b55019095315600f0c3ac8005a80f.
=> Revert "Switched emailbox"

app/config.js
Current prototype is showing up as dangerous, this is an attempt to get it showing up again
=> push to try and make prototype work

app/assets/sass/accounts.scss, app/data/session-data-defaults.js, app/routes.js, app/views/account/_account.html, app/views/account/change-password-1.html, app/views/account/change-password-2.html, app/views/account/change-password-3.html, app/views/account/cookie-feedback-settings.html, app/views/account/index.html, app/views/account/manage-account-2.html, app/views/email/admin/index.html, app/views/explore-header.html, app/views/layout-traditional.html, app/views/layout.html, app/views/notify/welcome.html, app/views/passenger-locator-form/delete-account-success.html, app/views/passenger-locator-form/delete-account.html, app/views/passenger-locator-form/home.html, app/views/passenger-locator-form/update-details.html, app/views/tasks.html
Added manage your data journeys:
- passenger locator form pages
- added 'You use these details to sign in to...' to manage page
Changed account navigation:
- removed side navigation
- added manage page to header
- renamed links to 'Account home' and 'Account settings'
=> Added manage your data journeys for UR in March

app/assets/sass/application.scss, app/views/layout-traditional.html, app/views/passenger-locator-form/home.html, app/views/tasks.html
changed task page, menu on PLF, and amends on PLF
=> tidy up for testing

app/views/account/change-password-1.html, app/views/account/change-password-2.html, app/views/account/change-password-3.html, app/views/notify/merged.html, app/views/tasks.html
- updated change password journey to match what is live
- updated email address on the merge email
- added PLF account home to task list
=> Small changes

README.md
A relatively pointless change, made to try and trigger a deploy on merge
to see if it works
=> Reflow readme
